const knowledgeBase = {
  "hi": "Hello! How can I assist you with your mobile services today?",
  "How to check my data balance?": "To check your data balance, dial *123# or use our mobile app for detailed information.",
  "How to activate roaming?": "You can activate roaming by dialing *456# or enabling it through the mobile app under 'Roaming Services'.",
  "What are the available data plans?": "We offer a range of data plans. Visit our website or dial *789# to explore the available plans.",
  "How to pay my bill?": "You can pay your bill through the mobile app, our website, or by dialing *101# and following the prompts.",
  "How to contact customer support?": "You can reach customer support by dialing 123 from your mobile or via our live chat on the website.",
  "How to activate a SIM card?": "To activate your new SIM card, insert it into your phone and dial *789# or use the instructions provided with the SIM.",
  "How to reset my voicemail password?": "To reset your voicemail password, dial 123 and follow the prompts, or reset it through the mobile app.",
  "What is the process to upgrade my mobile plan?": "You can upgrade your mobile plan by logging into the app, visiting our website, or dialing *111#.",
  "How to change my phone number?": "To change your phone number, contact customer support at 123, or visit the nearest store.",
  "What is the procedure to transfer my number to another provider?": "To port your number, you need to contact your new provider, and they will handle the process for you. You may also need to submit a request through your current provider.",
  "How to enable call forwarding?": "You can enable call forwarding by dialing **21*[phone number]# or through the settings in your phone.",
  "How to deactivate call forwarding?": "To deactivate call forwarding, dial ##21# or manage it from your phone's call settings.",
  "How to block a number?": "You can block a number by using your phone's built-in block feature or by contacting customer service to enable network-level blocking.",
  "What to do if my phone is lost or stolen?": "If your phone is lost or stolen, contact customer support immediately to suspend your services and protect your account.",
  "How to unlock my phone?": "To unlock your phone for use with another carrier, contact customer support to verify eligibility and get the unlock code.",
  "What are international roaming charges?": "International roaming charges depend on your location. Visit our website or contact support to learn about specific rates for your destination.",
  "How to set up a mobile hotspot?": "You can set up a mobile hotspot by going to your phone's settings, selecting 'Mobile Hotspot,' and enabling it.",
  "How to check my call history?": "To check your call history, log into the mobile app or website, or review your recent calls in your phone’s dialer app.",
  "How to redeem my rewards points?": "Redeem your rewards points through the mobile app under the 'Rewards' section or by visiting our website.",
  "How to upgrade my SIM card to 5G?": "Visit your nearest store or order a 5G-enabled SIM through our website or app. Once received, follow the activation instructions.",
  "How to check network coverage?": "Check network coverage by using the coverage map on our website or app. Enter your location to see the available coverage.",
  "How to disable voicemail?": "To disable voicemail, contact customer support or manage it through your phone's settings.",
  "How to request a bill extension?": "You can request a bill extension by contacting customer support or through the mobile app’s billing section.",
  "How to dispute a charge on my bill?": "If you need to dispute a charge, contact customer support with your billing details, and we will assist you with the process.",
  "How to add a family member to my plan?": "You can add a family member to your plan through the app, website, or by calling customer support to upgrade your account to a family plan.",
  "How to cancel my subscription?": "To cancel your subscription, contact customer support or use the cancellation option in the mobile app.",
  "How to view my payment history?": "To view your payment history, log in to the mobile app or visit the 'Billing' section on our website.",
  "How to activate a new device on my account?": "To activate a new device, insert your SIM card, and follow the setup instructions or contact customer support for assistance.",
  "How to upgrade my device?": "You can upgrade your device by visiting our store, the website, or using the mobile app to check for upgrade eligibility.",
  "How to add more data to my plan?": "You can add more data by purchasing a data add-on through the mobile app, dialing *789#, or visiting our website.",
  "How to enable parental controls?": "Enable parental controls by logging into the mobile app and selecting the 'Parental Controls' option in the settings.",
  "How to set up automatic payments?": "Set up automatic payments through the mobile app or website under the 'Billing' section.",
  "How to reset my account password?": "Reset your account password by selecting 'Forgot Password' on the login screen of the mobile app or website.",
  "How to enable Wi-Fi calling?": "Enable Wi-Fi calling through your phone’s settings under 'Network & Internet' or by contacting customer support.",
  "How to report network issues?": "Report network issues through the mobile app under 'Support' or by contacting customer service directly.",
  "How to track my data usage?": "Track your data usage in real-time through the mobile app or by dialing *123# for a quick summary.",
  "How to view my contract details?": "View your contract details by logging into your account on the mobile app or website, under the 'My Account' section.",
  "How to upgrade to unlimited data?": "Upgrade to an unlimited data plan by visiting the website or contacting customer support to change your plan.",
  "How to manage international calls?": "Manage international calls by dialing *456# to enable international calling services or by adjusting settings in the mobile app.",
  "How to reset network settings?": "Reset your network settings by going to your phone’s settings, selecting 'Reset Network Settings,' or contact support for guidance.",
  "How to deactivate call waiting?": "You can deactivate call waiting by dialing ##43# or managing the setting through your phone's call settings.",
  "How to replace my SIM card?": "Request a SIM card replacement by visiting our store or ordering one through the website or mobile app.",
  "How to manage notifications?": "Manage notifications through the app settings or by adjusting the notification preferences in your phone’s settings.",
  "How to block international calls?": "Block international calls by contacting customer support or by disabling the service through your mobile app’s settings.",
  "How to change my billing address?": "You can change your billing address through the mobile app or by visiting the 'Billing' section on our website.",
  "How to check mobile data speed?": "Check mobile data speed using speed test tools available on our website or through the mobile app.",
  "How to activate emergency alerts?": "Emergency alerts are automatically enabled. You can manage them through your phone’s settings under 'Notifications'.",
  "What to do if I don’t receive a bill?": "If you didn’t receive a bill, check your email or mobile app for a digital copy or contact support to resend it.",
  "How to manage roaming charges?": "Manage roaming charges by purchasing a roaming plan through the mobile app or by dialing *789# before traveling.",
  "How to report a service outage?": "Report a service outage through the mobile app under the 'Support' section or by contacting customer support.",
  "How to extend my prepaid balance validity?": "Extend your prepaid balance validity by recharging your account through the app or dialing *101# for recharge options.",
  "How to set up a custom voicemail greeting?": "Set up a custom voicemail greeting by dialing 123 and following the prompts or by accessing voicemail settings in the app.",
  "How to track my order?": "Track your order by visiting our website or app under the 'Order History' section or by using the tracking number sent to you via email.",
  "How to add a new payment method?": "You can add a new payment method in the 'Billing' section of the mobile app or website.",
  "How to activate Do Not Disturb (DND)?": "Activate Do Not Disturb by dialing *276# or through your phone’s settings under 'Call Settings'.",
  "How to check my SIM card number?": "Check your SIM card number by dialing *123# or by removing the SIM from your device to find the number printed on it.",
  "How to enable dual SIM settings?": "Enable dual SIM settings by accessing your phone’s network settings and selecting the options for managing both SIM cards.",
  "How to redeem a promo code?": "Redeem a promo code by entering it in the 'Promo' section of the app during checkout or by dialing the special promo code.",
  "How to activate a prepaid SIM card?": "Activate your prepaid SIM card by dialing *789# after inserting it into your phone, or follow the instructions in the package."
};

module.exports = { knowledgeBase };
